# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Corpus": "corpus.ipynb",
         "fast_replace": "corpus.ipynb",
         "dirichlet_likelihood": "dirichlet_likelihood.ipynb",
         "EmbedMixture": "embed_mixture.ipynb",
         "orthogonal_matrix": "fake_data.ipynb",
         "softmax": "fake_data.ipynb",
         "sample": "fake_data.ipynb",
         "fake_data": "fake_data.ipynb",
         "NegativeSamplingFunction": "negative_sampling.ipynb",
         "negative_sampling": "negative_sampling.ipynb",
         "negative_sampling.patched": "negative_sampling.ipynb",
         "L.NegativeSampling.negative_sampling": "negative_sampling.ipynb",
         "F.negative_sampling": "negative_sampling.ipynb",
         "tokenize": "preprocess.ipynb",
         "prob_words": "topics.ipynb",
         "prepare_topics": "topics.ipynb",
         "print_top_words_per_topic": "topics.ipynb",
         "get_request": "topics.ipynb",
         "topic_coherence": "topics.ipynb",
         "Tracking": "tracking.ipynb",
         "move": "utils.ipynb",
         "most_similar": "utils.ipynb",
         "chunks": "utils.ipynb",
         "MovingAverage": "utils.ipynb"}

modules = ["corpus.py",
           "dirichlet_likelihood.py",
           "embed_mixture.py",
           "fake_data.py",
           "negative_sampling.py",
           "preprocess.py",
           "topics.py",
           "tracking.py",
           "utils.py"]

doc_url = "https://JiaxiangBU.github.io/lda2vec/"

git_url = "https://github.com/JiaxiangBU/lda2vec/tree/master/"

def custom_doc_links(name): return None
